services:

  web:
    build: .
    env_file: .env
    command: gunicorn --workers 3 --bind 0.0.0.0:8001 --timeout 500 terraformus.wsgi:application
    volumes:
      - ./:/app
    expose:
      - 8001
    restart: unless-stopped
    network_mode: host
