version: '3.7'
services:
  terraformus_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./staticfiles:/app/staticfiles
      - .:/app
    ports:
      - "8002:8000"
