version: '3.7'

services:

  web:
    build: .
    env_file: .env
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --timeout 500 MIP.wsgi:application
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./:/app
    networks:
      - terraformus
    expose:
      - 8000
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./staticfiles:/app/staticfiles
    networks:
      - terraformus
    depends_on:
      - web

networks:
  terraformus:
