# Generated by Django 5.0.4 on 2024-05-23 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="author",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="ratingreply",
            old_name="author",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="author",
            new_name="user",
        ),
    ]
