# Generated by Django 5.0.4 on 2024-05-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_author_rating_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalasset",
            name="title",
            field=models.CharField(help_text="help text placeholder", max_length=255),
        ),
        migrations.AlterField(
            model_name="externalasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("doc", "Document"),
                    ("ref", "Reference"),
                    ("ex.", "Working example"),
                ],
                default="Document",
                help_text="help text placeholder",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="cost_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "0 - Requires time, effort and/or scrap material"),
                    (1, "$ - Up to USD 1.000 "),
                    (2, "$$ - Between USD 1.000 and USD 50.000"),
                    (3, "$$$ - Between USD 50.000 and USD 500.000"),
                    (4, "$$$$ - Over USD 500.000"),
                ],
                default="0 - Requires time, effort and/or scrap material",
                help_text="help text placeholder",
            ),
        ),
    ]
