# Generated by Django 5.0.4 on 2024-07-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lifecycle_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='extreme_poverty',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='lower_class',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='middle_class',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='upper_class',
        ),
    ]
