# Generated by Django 5.0.4 on 2024-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_solution_extreme_poverty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(blank=True, max_length=255, null=True)),
                ('home_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('what_is_the_platform_video', models.URLField(blank=True, null=True)),
                ('how_to_use_video', models.URLField(blank=True, null=True)),
                ('how_to_create_video', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
