# Generated by Django 5.0.4 on 2024-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_externalasset_title_alter_externalasset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='cost_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - Requires time, effort and/or scrap material'), (1, '$ - Up to USD 1.000 '), (2, '$$ - Between USD 1.000 and USD 50.000'), (3, '$$$ - Between USD 50.000 and USD 500.000'), (4, '$$$$ - Over USD 500.000')], default=0, help_text='What is the cost tier or your solution'),
        ),
    ]
